version: '2.3'

services:
  web-app:
    restart: always
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    image: web-app:master
    volumes:
      - .:/sova-asr
    command: bash -c "gunicorn --access-logfile - -w 1 --bind 0.0.0.0:8081 app:app --timeout 15000"
    ports:
      - 8081:8081

  classification-train:
    restart: "no"
    container_name: classification-train
    build:
      context: .
      dockerfile: Dockerfile.gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    image: classification-train:master
    volumes:
      - .:/sova-asr
    command: bash -c "python3 train.py /gjg/ 1000"
